### ISSUE TITLE
Set `this` to the emitter when calling listeners

### ISSUE THREAD

**Issue by ronkorving** [qubyte/vertebrate-event-emitter#3]
Right now, the fn.apply that is called doesn't set a `this` argument. One of the things I really do love about your typical EventEmitter is that you can count on `this` being the emitter. I understand that in the perfect ES6 world, you probably don't care too much, but it wouldn't cost much to get this for free I think.

**Comment by qubyte** [comment]
Good point. No guarantees (it might be that this adds a GC resistant reference), but the tests will pick that up! Will take a look. :+1:

**Comment by ronkorving** [comment]
It looks safe to me. You can just pass `this` to useCallback I think.

**Comment by qubyte** [comment]
@ronkorving See #4. I'm pretty sure this is what you mean. Can you confirm?

**Comment by ronkorving** [comment]
That is what I meant, although I would've just passed the thisArg rather than calling useCallback.call ;)
But that is your ... call.

**Comment by qubyte** [comment]
I totally dig `call` these days (although to be honest the thing that decided it was fewer lines in the diff on this occasion). :D

**Comment by qubyte** [comment]
Published v2.1.0 with this in.
